version: '3'
services:
 flask:
  build:
   context: app
   dockerfile: Dockerfile
  container_name: flask
  image: python:3.6
  restart: unless-stopped
  environment:
   APP_ENV: "dev"
   APP_DEBUG: "False"
   APP_PORT: 5000
   MONGODB_DATABASE: sopes1db
   MONGODB_USERNAME: mongodbuser
   MONGODB_PASSWORD: sopes1
   MONGODB_HOSTNAME: mongodb
  ports:
   - 5000:5000

  volumes:
    - ./app:/var/www
    - /proc:/var/www/fake_proc

  links:
    - mongodb

 mongodb:
  image: mongo:4.0.8
  container_name: mongodb
  restart: unless-stopped
  environment:
   MONGO_INITDB_DATABASE: sopes1db
   MONGODB_DATA_DIR: /data/db
   MONDODB_LOG_DIR: /dev/null
  volumes:
   - ./bd/mongodbdata:/data/db
  ports:
   - 27017:27017
